const IS_PENDING = "IS_PENDING";
const IS_REJECTED = "IS_REJECTED";
const ADD_EXERCISE = "ADD_EXERCISE";
const EDIT_EXERCISE = "EDIT_EXERCISE";
const SET_EXERCISES = "SET_EXERCISES";
const GET_EXERCISES = "GET_EXERCISES";
const DELETE_EXERCISE = "DELETE_EXERCISE";

export {
  IS_PENDING,
  IS_REJECTED,
  ADD_EXERCISE,
  EDIT_EXERCISE,
  SET_EXERCISES,
  GET_EXERCISES,
  DELETE_EXERCISE
};
