const IS_PENDING = "IS_PENDING";
const IS_REJECTED = "IS_REJECTED";
const SET_EXERCISES = "SET_EXERCISES";
const GET_EXERCISES = "GET_EXERCISES";
const ADD_EXERCISE = "ADD_EXERCISE";
const ADD_EXERCISE_FAILED = "ADD_EXERCISE_FAILED";
const ADD_EXERCISE_SUCCESS = "ADD_EXERCISE_SUCCESS";
const ADD_EXERCISE_RETRY = "ADD_EXERCISE_RETRY";
const EDIT_EXERCISE = "EDIT_EXERCISE";
const EDIT_EXERCISE_FAILED = "EDIT_EXERCISE_FAILED";
const EDIT_EXERCISE_SUCCESS = "EDIT_EXERCISE_SUCCESS";
const EDIT_EXERCISE_RETRY = "EDIT_EXERCISE_RETRY";
const DELETE_EXERCISE = "DELETE_EXERCISE";
const DELETE_EXERCISE_FAILED = "DELETE_EXERCISE_FAILED";
const DELETE_EXERCISE_SUCCESS = "DELETE_EXERCISE_SUCCESS";

export {
  IS_PENDING,
  IS_REJECTED,
  SET_EXERCISES,
  GET_EXERCISES,
  ADD_EXERCISE,
  ADD_EXERCISE_RETRY,
  ADD_EXERCISE_FAILED,
  ADD_EXERCISE_SUCCESS,
  EDIT_EXERCISE,
  EDIT_EXERCISE_RETRY,
  EDIT_EXERCISE_FAILED,
  EDIT_EXERCISE_SUCCESS,
  DELETE_EXERCISE,
  DELETE_EXERCISE_FAILED,
  DELETE_EXERCISE_SUCCESS
};
