const IS_PENDING = "IS_PENDING";
const IS_REJECTED = "IS_REJECTED";
const SET_HISTORY = "SET_HISTORY";
const ADD_DAY = "ADD_DAY";
const ADD_DAY_RETRY = "ADD_DAY_RETRY";
const ADD_DAY_FAILED = "ADD_DAY_FAILED";
const ADD_DAY_SUCCESS = "ADD_DAY_SUCCESS";
const DELETE_DAY = "DELETE_DAY";
const DELETE_DAY_FAILED = "DELETE_DAY_FAILED";
const DELETE_DAY_SUCCESS = "DELETE_DAY_SUCCESS";
const ADD_EXERCISE = "ADD_EXERCISE";
const ADD_EXERCISE_RETRY = "ADD_EXERCISE_RETRY";
const ADD_EXERCISE_FAILED = "ADD_EXERCISE_FAILED";
const ADD_EXERCISE_SUCCESS = "ADD_EXERCISE_SUCCESS";
const DELETE_EXERCISE = "DELETE_EXERCISE";
const DELETE_EXERCISE_RETRY = "DELETE_EXERCISE_RETRY";
const DELETE_EXERCISE_FAILED = "DELETE_EXERCISE_FAILED";
const DELETE_EXERCISE_SUCCESS = "DELETE_EXERCISE_SUCCESS";
const DELETE_EXERCISES = "DELETE_EXERCISES";
const DELETE_EXERCISES_RETRY = "DELETE_EXERCISES_RETRY";
const DELETE_EXERCISES_FAILED = "DELETE_EXERCISES_FAILED";
const DELETE_EXERCISES_SUCCESS = "DELETE_EXERCISES_SUCCESS";
const EDIT_SET = "EDIT_SET";
const EDIT_SET_RETRY = "EDIT_SET_RETRY";
const EDIT_SET_FAILED = "EDIT_SET_FAILED";
const EDIT_SET_SUCCESS = "EDIT_SET_SUCCESS";
const ADD_SET = "ADD_SET";
const ADD_SET_RETRY = "ADD_SET_RETRY";
const ADD_SET_FAILED = "ADD_SET_FAILED";
const ADD_SET_SUCCESS = "ADD_SET_SUCCESS";
const DELETE_SET = "DELETE_SET";
const DELETE_SET_RETRY = "DELETE_SET_RETRY";
const DELETE_SET_FAILED = "DELETE_SET_FAILED";
const DELETE_SET_SUCCESS = "DELETE_SET_SUCCESS";
const COPY_DAY = "COPY_DAY";
const REQUEST_FAILED = "REQUEST_FAILED";

export {
  IS_PENDING,
  IS_REJECTED,
  SET_HISTORY,
  ADD_DAY,
  ADD_DAY_RETRY,
  ADD_DAY_FAILED,
  ADD_DAY_SUCCESS,
  DELETE_DAY,
  DELETE_DAY_FAILED,
  DELETE_DAY_SUCCESS,
  ADD_EXERCISE,
  ADD_EXERCISE_RETRY,
  ADD_EXERCISE_FAILED,
  ADD_EXERCISE_SUCCESS,
  DELETE_EXERCISE,
  DELETE_EXERCISE_RETRY,
  DELETE_EXERCISE_FAILED,
  DELETE_EXERCISE_SUCCESS,
  DELETE_EXERCISES,
  DELETE_EXERCISES_RETRY,
  DELETE_EXERCISES_FAILED,
  DELETE_EXERCISES_SUCCESS,
  ADD_SET,
  ADD_SET_RETRY,
  ADD_SET_FAILED,
  ADD_SET_SUCCESS,
  EDIT_SET,
  EDIT_SET_RETRY,
  EDIT_SET_FAILED,
  EDIT_SET_SUCCESS,
  DELETE_SET,
  DELETE_SET_RETRY,
  DELETE_SET_FAILED,
  DELETE_SET_SUCCESS,
  COPY_DAY,
  REQUEST_FAILED
};
