const IS_PENDING = "IS_PENDING";
const IS_REJECTED = "IS_REJECTED";
const SET_HISTORY = "SET_HISTORY";
const ADD_DAY = "ADD_DAY";
const DELETE_DAY = "DELETE_DAY";
const ADD_EXERCISE = "ADD_EXERCISE";
const DELETE_EXERCISE = "DELETE_EXERCISE";
const DELETE_EXERCISES = "DELETE_EXERCISES";
const EDIT_SET = "EDIT_SET";
const ADD_SET = "ADD_SET";
const DELETE_SET = "DELETE_SET";
const COPY_DAY = "COPY_DAY";
const REQUEST_FAILED = "REQUEST_FAILED";

export {
  IS_PENDING,
  IS_REJECTED,
  SET_HISTORY,
  ADD_DAY,
  DELETE_DAY,
  ADD_EXERCISE,
  DELETE_EXERCISE,
  DELETE_EXERCISES,
  ADD_SET,
  EDIT_SET,
  DELETE_SET,
  COPY_DAY,
  REQUEST_FAILED
};
