const IS_RED = "IS_RED";
const IS_WHITE = "IS_WHITE";
const SHOW_BACK = "SHOW_BACK";
const SINGLE_NAV = "SINGLE_NAV";
const DOUBLE_NAV = "DOUBLE_NAV";
const SHOW_DEHAZE = "SHOW_DEHAZE";

export { IS_RED, IS_WHITE, SINGLE_NAV, DOUBLE_NAV, SHOW_BACK, SHOW_DEHAZE };
