const IS_RED = "IS_RED";
const IS_WHITE = "IS_WHITE";
const SHOW = "SHOW";
const SHOW_BACK = "SHOW_BACK";
const SHOW_NONE = "SHOW_NONE";
const SHOW_DEHAZE = "SHOW_DEHAZE";

export { IS_RED, IS_WHITE, SHOW, SHOW_NONE, SHOW_BACK, SHOW_DEHAZE };
