const SHOW = "SHOW";
const SHOW_BACK = "SHOW_BACK";
const SHOW_NONE = "SHOW_NONE";
const SHOW_DEHAZE = "SHOW_DEHAZE";
const CLEAN_STATE = "CLEAN_STATE";

const SET_PLAN_BACKLINK = "SET_PLAN_BACKLINK";

export {
  SHOW,
  SHOW_NONE,
  SHOW_BACK,
  SHOW_DEHAZE,
  CLEAN_STATE,
  SET_PLAN_BACKLINK
};
