const IS_PENDING = "IS_PENDING";
const IS_REJECTED = "IS_REJECTED";
const SET_PLAN = "SET_PLAN";
const EDIT_PLAN = "EDIT_PLAN";
const ADD_WEEK = "ADD_WEEK";
const COPY_WEEK = "COPY_WEEK";
const REPEAT_WEEK = "REPEAT_WEEK";
const DELETE_WEEK = "DELETE_WEEK";
const ADD_EXERCISE = "ADD_EXERCISE";
const EDIT_EXERCISE = "EDIT_EXERCISE";
const DELETE_EXERCISE = "DELETE_EXERCISE";
const ADD_SET = "ADD_SET";
const EDIT_SET = "EDIT_SET";
const DELETE_SET = "DELETE_SET";

export {
  IS_PENDING,
  IS_REJECTED,
  SET_PLAN,
  EDIT_PLAN,
  ADD_WEEK,
  COPY_WEEK,
  REPEAT_WEEK,
  DELETE_WEEK,
  ADD_EXERCISE,
  EDIT_EXERCISE,
  DELETE_EXERCISE,
  ADD_SET,
  EDIT_SET,
  DELETE_SET
};
