const IS_PENDING = "IS_PENDING";
const IS_REJECTED = "IS_REJECTED";
const SET_PLANS = "SET_PLANS";
const ADD_PLAN = "ADD_PLAN";
const ACTIVATE_PLAN = "ACTIVATE_PLAN";

export { IS_PENDING, IS_REJECTED, SET_PLANS, ADD_PLAN, ACTIVATE_PLAN };
