const IS_PENDING = "IS_PENDING";
const IS_REJECTED = "IS_REJECTED";
const SET_PLAN = "SET_PLAN";
const EDIT_PLAN = "EDIT_PLAN";
const ADD_WEEK = "ADD_WEEK";
const EDIT_WEEK = "EDIT_WEEK";
const DELETE_WEEK = "DELETE_WEEK";
const ADD_EXERCISE = "ADD_EXERCISE";
const EDIT_EXERCISE = "EDIT_EXERCISE";
const DELETE_EXERCISE = "DELETE_EXERCISE";

export {
  IS_PENDING,
  IS_REJECTED,
  SET_PLAN,
  EDIT_PLAN,
  ADD_WEEK,
  EDIT_WEEK,
  DELETE_WEEK,
  ADD_EXERCISE,
  EDIT_EXERCISE,
  DELETE_EXERCISE
};
