const SET_PROFILE = "SET_PROFILE";
const IS_PENDING = "IS_PENDING";
const IS_REJECTED = "IS_REJECTED";
const EDIT_PROFILE = "EDIT_PROFILE";

export { SET_PROFILE, IS_PENDING, IS_REJECTED, EDIT_PROFILE };
