const SET_USER = "SET_USER";
const IS_PENDING = "IS_PENDING";
const IS_REJECTED = "IS_REJECTED";
const EDIT_USER = "EDIT_USER";
const ACTIVATE_PLAN = "ACTIVATE_PLAN";
const DEACTIVATE_PLAN = "DEACTIVATE_PLAN";
const REQUEST_FAILED = "REQUEST_FAILED";

export {
  SET_USER,
  EDIT_USER,
  IS_PENDING,
  IS_REJECTED,
  ACTIVATE_PLAN,
  DEACTIVATE_PLAN,
  REQUEST_FAILED
};
