const IS_PENDING = "IS_PENDING";
const IS_REJECTED = "IS_REJECTED";
const SET_ACCESS = "SET_ACCESS";
const ADD_PLAN = "ADD_PLAN";
const REMOVE_PLAN = "REMOVE_PLAN";
const REQUEST_FAILED = "REQUEST_FAILED";

export {
  IS_PENDING,
  IS_REJECTED,
  SET_ACCESS,
  ADD_PLAN,
  REMOVE_PLAN,
  REQUEST_FAILED
};
