export const IS_PENDING = "IS_PENDING";
export const IS_REJECTED = "IS_REJECTED";
export const SET_ACCESS = "SET_ACCESS";
export const ADD_PLAN_SUCCESS = "ADD_PLAN_SUCCESS";
export const REMOVE_PLAN_SUCCESS = "REMOVE_PLAN_SUCCESS";
export const REQUEST_FAILED = "REQUEST_FAILED";
