export const SET_USER = "SET_USER";
export const IS_PENDING = "IS_PENDING";
export const IS_REJECTED = "IS_REJECTED";
export const EDIT_USER = "EDIT_USER";
export const EDIT_USER_FAILED = "EDIT_USER_FAILED";
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";
export const ACTIVATE_PLAN_SUCCESS = "ACTIVATE_PLAN";
export const DEACTIVATE_PLAN_SUCCESS = "DEACTIVATE_PLAN";
