const SET_USER = "SET_USER";
const IS_PENDING = "IS_PENDING";
const IS_REJECTED = "IS_REJECTED";
const EDIT_USER = "EDIT_USER";
const EDIT_USER_FAILED = "EDIT_USER_FAILED";
const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";
const ACTIVATE_PLAN = "ACTIVATE_PLAN";
const DEACTIVATE_PLAN = "DEACTIVATE_PLAN";

export {
  SET_USER,
  EDIT_USER,
  EDIT_USER_FAILED,
  EDIT_USER_SUCCESS,
  IS_PENDING,
  IS_REJECTED,
  ACTIVATE_PLAN,
  DEACTIVATE_PLAN
};
