const IS_PENDING = "IS_PENDING";
const IS_REJECTED = "IS_REJECTED";
const SET_EXERCISES = "SET_EXERCISES";
const GET_EXERCISES = "GET_EXERCISES";

export { IS_PENDING, IS_REJECTED, SET_EXERCISES, GET_EXERCISES };
